//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOffice.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.TaskAssignees = new HashSet<TaskAssignee>();
            this.TaskDocuments = new HashSet<TaskDocument>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int DepartmentId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> TaskTypeId { get; set; }
        public int StatusId { get; set; }
        public int Order { get; set; }
        public int Priority { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> Estimated { get; set; }
        public Nullable<int> TimeSpent { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int CustomerId { get; set; }
        public string ContactInformation { get; set; }
        public int Rating { get; set; }
        public string Result { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime EditedOn { get; set; }
        public string EditedBy { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Project Project { get; set; }
        public virtual TaskType TaskType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskAssignee> TaskAssignees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskDocument> TaskDocuments { get; set; }
    }
}
